mini-os: GCC 7.2 requires __divmoddi4
Some code compiled by gcc 7 requires this.

xen-git/stubdom/mini-os-x86_32-grub/mini-os.o: In function `blkfront_posix_rwop':
xen-git/extras/mini-os-remote/blkfront.c:624: undefined reference to `__divmoddi4'

Signed-off-by: Eric Chanudet <chanudete@ainfosec.com>